-- Masar School Management - initial PostgreSQL/Supabase schema
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null check (role in ('admin','teacher','parent')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists academic_years (
  id bigint generated by default as identity primary key,
  name text not null unique,
  start_date date not null,
  end_date date not null,
  is_active boolean not null default false
);

create table if not exists grades (
  id bigint generated by default as identity primary key,
  academic_year_id bigint not null references academic_years(id) on delete cascade,
  name text not null,
  level smallint not null,
  unique(academic_year_id,name)
);

create table if not exists sections (
  id bigint generated by default as identity primary key,
  grade_id bigint not null references grades(id) on delete cascade,
  name text not null,
  unique(grade_id,name)
);

create table if not exists subjects (
  id bigint generated by default as identity primary key,
  name text not null unique,
  code text unique,
  is_active boolean not null default true
);

create table if not exists teachers (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references profiles(id) on delete cascade,
  employee_code text unique,
  phone text,
  specialization text
);

create table if not exists students (
  id bigint generated by default as identity primary key,
  section_id bigint not null references sections(id),
  student_code text not null unique,
  full_name text not null,
  gender text,
  birth_date date,
  phone text,
  address text,
  status text not null default 'active'
);

create table if not exists teacher_assignments (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references teachers(id),
  subject_id bigint not null references subjects(id),
  section_id bigint not null references sections(id),
  academic_year_id bigint not null references academic_years(id),
  start_date date not null,
  end_date date,
  status text not null default 'active',
  unique(teacher_id,subject_id,section_id,academic_year_id,start_date)
);

create table if not exists timetable (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references teacher_assignments(id) on delete cascade,
  day_of_week smallint not null check(day_of_week between 0 and 6),
  period_number smallint not null check(period_number between 1 and 12),
  room text,
  unique(day_of_week,period_number,room)
);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  student_id bigint not null references students(id) on delete cascade,
  assignment_id bigint not null references teacher_assignments(id),
  attendance_date date not null,
  status text not null check(status in ('present','absent','late','excused')),
  note text,
  entered_by uuid not null references profiles(id),
  created_at timestamptz not null default now(),
  unique(student_id,assignment_id,attendance_date)
);

create table if not exists exams (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references teacher_assignments(id),
  name text not null,
  exam_type text,
  exam_date date,
  max_score numeric(7,2) not null,
  created_by uuid not null references profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists scores (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references exams(id) on delete cascade,
  student_id bigint not null references students(id) on delete cascade,
  score numeric(7,2),
  note text,
  entered_by uuid not null references profiles(id),
  entered_at timestamptz not null default now(),
  unique(exam_id,student_id)
);

-- Core permission helper: teacher can only act inside an active assignment.
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin' and p.is_active=true);
$$;

create or replace function public.teacher_can_access_assignment(p_assignment_id bigint)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(
    select 1 from teacher_assignments ta
    join teachers t on t.id=ta.teacher_id
    where ta.id=p_assignment_id
      and t.user_id=auth.uid()
      and ta.status='active'
      and ta.start_date<=current_date
      and (ta.end_date is null or ta.end_date>=current_date)
  );
$$;

alter table profiles enable row level security;
alter table students enable row level security;
alter table teacher_assignments enable row level security;
alter table timetable enable row level security;
alter table attendance enable row level security;
alter table exams enable row level security;
alter table scores enable row level security;

create policy "profiles self or admin" on profiles for select using (id=auth.uid() or public.is_admin());
create policy "students admin select" on students for select using (public.is_admin());
create policy "students teacher assigned select" on students for select using (
  public.is_admin() or exists(
    select 1 from teacher_assignments ta join teachers t on t.id=ta.teacher_id
    where ta.section_id=students.section_id and t.user_id=auth.uid() and ta.status='active'
  )
);
create policy "assignments own or admin" on teacher_assignments for select using (
  public.is_admin() or exists(select 1 from teachers t where t.id=teacher_assignments.teacher_id and t.user_id=auth.uid())
);
create policy "attendance select allowed" on attendance for select using (public.is_admin() or public.teacher_can_access_assignment(assignment_id));
create policy "attendance insert allowed" on attendance for insert with check (public.is_admin() or (public.teacher_can_access_assignment(assignment_id) and entered_by=auth.uid()));
create policy "attendance update allowed" on attendance for update using (public.is_admin() or public.teacher_can_access_assignment(assignment_id));
create policy "exams allowed" on exams for all using (public.is_admin() or public.teacher_can_access_assignment(assignment_id)) with check (public.is_admin() or public.teacher_can_access_assignment(assignment_id));
create policy "scores select allowed" on scores for select using (public.is_admin() or exists(select 1 from exams e where e.id=scores.exam_id and public.teacher_can_access_assignment(e.assignment_id)));
create policy "scores insert allowed" on scores for insert with check (public.is_admin() or exists(select 1 from exams e where e.id=scores.exam_id and public.teacher_can_access_assignment(e.assignment_id)));
